server:
  port: 8000

spring:
  application:
    name: "gateway-service"

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
            - AddRequestHeader=token, 1234
            - AddResponseHeader=authenticated, yes

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filter:
            - RewritePath=/order/?(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true