server:
  port: 64412


eureka:
  instance:
    instance-id: "user-microservice-instance"

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: "user-service"